<?xml version="1.0"?>
<robot name="myscar" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="height" value="0.7" />

    <!-- Define material to paint the links -->
    <material name="yellow">
        <color rgba="0.8 0.8 0 0.5"/>
    </material>

    <material name="blue">
        <color rgba="0 0.8 0.8 0.5"/>
    </material>

    <material name="pink">
        <color rgba="1 0.4 0.7 0.5"/>
    </material>

    <material name="green">
        <color rgba="0 1 0 0.5"/>
    </material>


    <!-- Define links and joints -->

    <link name="base_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 ${height/2}" />
            <geometry>
                <cylinder length="${height}" radius="0.2"/>
            </geometry>
            <material name="yellow"/>
        </visual>
    </link>

    <link name="link1">
        <visual>
            <origin rpy="0 0 0" xyz="1.0 0 0.1" />
            <geometry>
                <box size="2.0 0.3 0.2"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="base_link_to_link1" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="0.0" upper="6.28" velocity="0.5"/>
        <origin rpy="0 0 0" xyz="0 0 0.65"/>
        <parent link="base_link"/>
        <child link="link1"/>
    </joint>

    <link name="link1b">
        <visual>
         <origin rpy="0 0 0" xyz="0 0 0.15" />
            <geometry>
                <cylinder length="0.3" radius="0.2"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="link1_to_link1b" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 -0.05"/>
        <parent link="link1"/>
        <child link="link1b"/>
    </joint>

    <link name="link2">
        <visual>
            <origin xyz="1.0 0 0.1"/>
            <geometry>
                <box size = "2.0 0.3 0.2" />
            </geometry>
            <material name = 'pink'/>
        </visual>
    </link>

    <joint name="link1_to_link2" type="continuous">
        <parent link="link1"/>
        <child link="link2"/>
        <axis xyz="0 0 1"/>
        <origin rpy="0 0 0" xyz="2 0 0" />
    </joint>

    <link name="link2b">
        <visual>
            <origin xyz="0 0 0.15"/>
            <geometry>
                <cylinder length="0.3" radius="0.2" />
            </geometry>
            <material name = 'pink'/>
        </visual>
    </link>

    <joint name="link2_to_link2b" type="fixed">
        <parent link="link2"/>
        <child link="link2b"/>
        <origin xyz="0 0 -0.05"/>
    </joint>

    <link name="eelink">
        <visual>
            <origin xyz="0 0 -0.3"/>
            <geometry>
                <cylinder length="0.6" radius="0.05" />
            </geometry>
            <material name = 'green'/>
        </visual>
    </link>

    <joint name="link2_to_eelink" type="prismatic">
        <parent link="link2"/>
        <child link="eelink"/>
        <limit effort="1000.0" lower="0" upper="0.6" velocity="0.5"/>
        <axis xyz="0 0 1"/>
        <origin xyz="2 0 0"/>
    </joint>

    <link name="eelinkb">
        <visual>
            <origin xyz="0 0 0.1"/>
            <geometry>
                <cylinder length="0.3" radius="0.2" />
            </geometry>
            <material name = 'pink'/>
        </visual>
    </link>

    <joint name="link2_to_eelinkb" type="fixed">
        <parent link="link2"/>
        <child link="eelinkb"/>
        <origin xyz="2 0 0"/>
    </joint>


</robot>
